### ISSUE TITLE
Classic parser tag arguments not interpreted correctly

### ISSUE THREAD

**Issue by JohnRDOrazio** [StarCitizenWiki/mediawiki-extensions-EmbedVideo#12]
**Describe the bug**
It seems that the arguments are not being read correctly, or in the correct order, when using the classic `#ev` parser tag.

**To Reproduce**
1. Insert a classic parser tag for youtube on the page, such as `{{#ev:youtube|oCghUlTLKVA||center|||rel=0&enablejsapi=1&origin=https://mywiki.example}}`
2. Save the page
3. See error `EmbedVideo was given an illegal value for the valignment parameter "rel=0&enablejsapi=1&origin=https://mywiki.example". Valid values are "top", "middle", "bottom", or "baseline".`

**Expected behavior**
The arguments should be read in this order:
```
{{#ev:service|id|dimensions|alignment|description|container|urlargs|autoresize}}
```
Between `alignment` and `urlargs` there should be two arguments `description` and `container`. If these are not used, there should be three pipes. However the only way to get rid of this error is to remove a pipe, and put the `urlargs` in the place of  the `container` argument. However this would require updating all `#ev` parser tags on all wiki pages.

**Screenshots**
![Immagine 2021-10-06 022515](https://user-images.githubusercontent.com/231298/136121766-e525fd07-ecdc-42de-b4d2-c2e6bfe6fc30.jpg)

**Technical information:**
 - OS: Ubuntu 20.04
 - Browser: chrome
 - Extension Version: v3.0.4
 - MediaWiki Version: v1.36.2
 - Host type: dedicated

**Additional context**

**Comment by octfx** [comment]
Thanks for thorough report!  
The passed arguments should now be read in the expected order.
Would you mind testing the current develop branch?

**Comment by octfx** [comment]
Perfect, I'll tag the next version later today

Am 6. Oktober 2021 19:09:30 MESZ schrieb JohnRDOrazio ***@***.***>:
>I can confirm that 04f9a207aff46e7eeae53c4f076999d4a33ee8da fixes this issue
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/StarCitizenWiki/mediawiki-extensions-EmbedVideo/issues/12#issuecomment-936711440
-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.
