### ISSUE TITLE
Update Examples

### ISSUE THREAD

**Issue by Jerimee** [StarCitizenWiki/mediawiki-extensions-EmbedVideo#16]
## Detailed Description
The 7 examples are useful, and even more would be great. YouTube is the used as the service, and this is confusing because some of the examples imply functionality which YouTube does not in fact allow. For example, cover and title are not supported: https://developers.google.com/youtube/player_parameters#Parameters

## Context
README.md are the example users rely on to test the ext and implement it.

As an anecdote, I have no clue how to use EV with twitch as the service, since the examples don't seem relevant to that service.

## Possible Implementation
Example 6 should not be `{{#ev:youtube|eAORm-8b1Eg|cover=File:LocalFile.jpg|title=Title of the Embed}}` but instead a service that does allow these features.

It would be good if links to the actual output result - the video player with the video - could be provided.

And it would be ideal if examples for each service can be provided.

Would you like me to submit a PR improving the examples? I would probably change the examples section to a new file EXAMPLES.md and link to it from the README.md

**Comment by Jerimee** [comment]
I am referring to this section: https://github.com/StarCitizenWiki/mediawiki-extensions-EmbedVideo#examples

**Comment by octfx** [comment]
A PR is more than welcome!

regarding the `cover` and `title` parameters, those are accepted globally for each service.
They allow to specify a local file and a manual title, when fetching of external content is disabled.

But you are right, the documentation is lacking in a lot of areas

**Comment by Jerimee** [comment]
Can you tell me how to test/demo that? Is there manner by which I can manually disable the external content, so I can see how the cover and title look?

**Comment by octfx** [comment]
The readme contains a table describing all available settings.  The last two entries are related to external content

one example wiki that uses local files as cover images is https://hololive.wiki/wiki/Main_Page

**Comment by Jerimee** [comment]
Now I see; this: $wgEmbedVideoFetchExternalThumbnails

**Comment by Jerimee** [comment]
Sorry I apologize for all the support requests.

On this page - http://ephemeralfilm.info/index.php?title=User:JJR/evexamples#Example_6 - I cannot figure out how to display anything for cover, title, or thumbnail.  I thought this was simply because yt didn't allow them.

I have 
$wgEmbedVideoRequireConsent	= true;
$wgEmbedVideoFetchExternalThumbnails = false;

I looked at the https://hololive.wiki/ but I couldn't find an example there either - I view the source of 10 or so of the videos... - can you give me a more specific url?

**Comment by octfx** [comment]
No problem, happy to help

is there a file uploaded to the wiki called `LocalFile.jpg`?

the extensions tries to use a file uploaded to the wiki as an alternative thumbnail. The name used in the `cover` argument must match the name of the uploaded file

**Comment by Jerimee** [comment]
Thanks

http://ephemeralfilm.info/index.php?title=File:LocalFile.jpg

**Comment by octfx** [comment]
One example from the hololive wiki is https://hololive.wiki/wiki/Ouro_Kronii

**Comment by Jerimee** [comment]
The title they assigned, and the cover they assigned, are exactly identical to what YouTube shows by default.

Their code did not work on my wiki, even when I swapped out the file name. `{{#ev:youtube|W3oVrq94mGM|480|cover=File:LocalFile.jpg|title=a title is me}}`
http://ephemeralfilm.info/index.php?title=User:JJR/evexamples#Example_5c

Oh but if you view the html source of that page you see the html - so that is something!

**Comment by Jerimee** [comment]
Maybe something is off about how my files/images are configured on my wiki

**Comment by Jerimee** [comment]
Yeah, mine never show this attribute embedvideo-consent__title

**Comment by octfx** [comment]
This was indeed a bug! 
Current develop should contain the fix

**Comment by ThermoMan** [comment]
I just came to the help page looking for an example - having just switched from the older/main EmbedVideo to this one.

On a wiki I maintain we had a page of links with a central player window at the top.
```
<div class='ev-container'><div class='ev-inner'>
<evlplayer id='youtube' w='400' h='200' id='p1'></evlplayer>
</div></div>
```

With the various referenced videos below that
```
* {{#evl:P_SlAzsXa7E|Genghis Khan||player=p1}}
* {{#evl:RRKJiM9Njr8|The Black Parade||player=p1}}
* {{#evl:J9Q3i5w6-Ug|Starlight Brigade||player=p1}}
```

Each of these when clicked would cause the single player window to begin the requested video.  Is this function (play in a separate video box) one of the things that this version doesn't have or do I just need to learn the right incantation to do it again?

**Comment by octfx** [comment]
Sorry that this is not mentioned in the readme, from the MediaWiki Extension page:
> Moreover, it only supports parser function #ev and the corresponding service tag.

As part of the refactor and code-base slimming, for now only the `#ev` parser function and service tags like `<youtube>` are supported

**Comment by ThermoMan** [comment]
Thanks for the quick reply.  I had sort of feared that was the answer and already refactored the wiki pages that used the videolink feature.
