### ISSUE TITLE
support request - what is oembed

### ISSUE THREAD

**Issue by Jerimee** [StarCitizenWiki/mediawiki-extensions-EmbedVideo#19]
Is oEmbed presently supported?

Is the code within YouTubeOEmbed.php merely an example place holder, as the code suggests, or is there an option to display youtube as oEmbed?

> oEmbed is a format for allowing an embedded representation of a URL on third party sites.

What is the use case for this? Can oEmbed be used to help circumvent or comply with content-security-policy (CSP)?

Within my limited ability, I will attempt to add any insight provided here to the Readme file :)

**Comment by Jerimee** [comment]
a clue = Classes implementing this interface retrieve their html by calling the OEmbed endpoint

**Comment by Jerimee** [comment]
Related support requestion question:

EmbedHtmlFormatter.php at around line 36

`		if ( $service instanceof OEmbedServiceInterface ) {
			// I think this is never true as of 2021-11-22
			try {
				$data = OEmbed::newFromRequest( $service->getUrl() );
				return $data->getHtml();
			} catch ( UnexpectedValueException $e ) {
				return $e->getMessage();
			}
		} else {
			// so is it always an instance of AbstractEmbedService ?
			if ($jjrDebug == 1) {
				$consoleOutput[] = 'not oembed';
				if ( $service instanceof AbstractEmbedService ) {
					// I think this is always true as of 2021-11-22
					$consoleOutput[] = 'is abstract service';
				}
			}
		}`

The comments and the else are my own _(amateur hour)_ additions to try to understand the code. 

These are my related questions:

1. Is there any state where service is an instance of OEmbedServiceInterface?
2. Is there any state where service is not an instance of AbstractEmbedService?

**Comment by octfx** [comment]
> Is oEmbed presently supported?
There is currently no service implementing the OEmbed Interface, it is old functionality from EmbedVideo <v3.0.  
I decided against removing it, as future services may want to implement this (?)

> What is the use case for this? Can oEmbed be used to help circumvent or comply with content-security-policy (CSP)?
The idea behind oembed is, that you only need an url pointing to an embed, and the requested site generates all necessary parameters.

As an example you can view the following [YouTube oEmbed](https://www.youtube.com/oembed?type=json&url=http://www.youtube.com/watch?v=PVzljDmoPVs) for http://www.youtube.com/watch?v=PVzljDmoPVs: 
```json
{
    "title": "David Guetta - She Wolf (Falling To Pieces) ft. Sia (Official Video)",
    "author_name": "David Guetta",
    "author_url": "https://www.youtube.com/c/davidguetta",
    "type": "video",
    "height": 113,
    "width": 200,
    "version": "1.0",
    "provider_name": "YouTube",
    "provider_url": "https://www.youtube.com/",
    "thumbnail_height": 360,
    "thumbnail_width": 480,
    "thumbnail_url": "https://i.ytimg.com/vi/PVzljDmoPVs/hqdefault.jpg",
    "html": "\u003ciframe width=\u0022200\u0022 height=\u0022113\u0022 src=\u0022https://www.youtube.com/embed/PVzljDmoPVs?feature=oembed\u0022 frameborder=\u00220\u0022 allow=\u0022accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\u0022 allowfullscreen\u003e\u003c/iframe\u003e"
}
```

The last key `hml` contains everything necessary for the embed to work.

This is in contrast to all other services that do not implement OEmbedInterface, those services explicitly define widht, height, url validations, id validations, etc.

For OEmbed services. the the wiki internally makes a request to the defined oembed service, retrieves the html from the response, and rerturns it.

See the following execution flow:
1. [EmbedVideo.php#L107 (Parser function entry)](https://github.com/StarCitizenWiki/mediawiki-extensions-EmbedVideo/blob/develop/includes/EmbedVideo.php#L107)
2. [EmbedVideo.php#183 (output generation)](https://github.com/StarCitizenWiki/mediawiki-extensions-EmbedVideo/blob/develop/includes/EmbedVideo.php#L155)
3. [EmbedHtmlFormatter.php#L33 (OEmbed check)](https://github.com/StarCitizenWiki/mediawiki-extensions-EmbedVideo/blob/develop/includes/EmbedService/EmbedHtmlFormatter.php#L33)
4. [EmbedHtmlFormatter.php#L87 (OEmbed request is sent](https://github.com/StarCitizenWiki/mediawiki-extensions-EmbedVideo/blob/develop/includes/EmbedService/EmbedHtmlFormatter.php#L87)

> Is there any state where service is an instance of OEmbedServiceInterface?
Currently no

> Is there any state where service is not an instance of AbstractEmbedService?
No, every service must extend `AbstractEmbedService` this is the base class for every embed.  
Even services that want to utilise OEmbed functionality must extend it (and further implement OEmbedInterface)
