### ISSUE TITLE
Error on uploading a .mp4 file using version 3.0.7 

### ISSUE THREAD

**Issue by cruxicheiros** [StarCitizenWiki/mediawiki-extensions-EmbedVideo#20]
I get this error when uploading to Special:Upload. I was able to fix the problem by downgrading to version 3.0.6. This is my first time using this plugin and I don't know enough about the setup to be able to tell exactly what the problem is, but I thought you should know so that you could sort it out. Thanks :)

> ```[YfAWRHxGhjnZy91WiEnHigAAAAU] /index.php/Special:Upload Error: Call to undefined method FSFile::getTitle()
> 
> Backtrace:
> 
> from /var/www/ndamediawiki/html/extensions/EmbedVideo/includes/Media/FFProbe/FFProbe.php(68)
> #0 /var/www/ndamediawiki/html/includes/libs/objectcache/wancache/WANObjectCache.php(1700): MediaWiki\Extension\EmbedVideo\Media\FFProbe\FFProbe->MediaWiki\Extension\EmbedVideo\Media\FFProbe\{closure}()
> #1 /var/www/ndamediawiki/html/includes/libs/objectcache/wancache/WANObjectCache.php(1532): WANObjectCache->fetchOrRegenerate()
> #2 /var/www/ndamediawiki/html/extensions/EmbedVideo/includes/Media/FFProbe/FFProbe.php(80): WANObjectCache->getWithSetCallback()
> #3 /var/www/ndamediawiki/html/extensions/EmbedVideo/includes/Media/FFProbe/FFProbe.php(104): MediaWiki\Extension\EmbedVideo\Media\FFProbe\FFProbe->getMetaData()
> #4 /var/www/ndamediawiki/html/extensions/EmbedVideo/includes/Media/AudioHandler.php(316): MediaWiki\Extension\EmbedVideo\Media\FFProbe\FFProbe->getStream()
> #5 /var/www/ndamediawiki/html/extensions/EmbedVideo/includes/Media/AudioHandler.php(273): MediaWiki\Extension\EmbedVideo\Media\AudioHandler->getFFProbeResult()
> #6 /var/www/ndamediawiki/html/includes/media/MediaHandler.php(236): MediaWiki\Extension\EmbedVideo\Media\AudioHandler->getMetadata()
> #7 /var/www/ndamediawiki/html/includes/utils/MWFileProps.php(88): MediaHandler->getSizeAndMetadataWithFallback()
> #8 /var/www/ndamediawiki/html/includes/upload/UploadBase.php(552): MWFileProps->getPropsFromPath()
> #9 /var/www/ndamediawiki/html/includes/upload/UploadBase.php(485): UploadBase->verifyPartialFile()
> #10 /var/www/ndamediawiki/html/includes/upload/UploadBase.php(391): UploadBase->verifyFile()
> #11 /var/www/ndamediawiki/html/includes/upload/UploadFromFile.php(95): UploadBase->verifyUpload()
> #12 /var/www/ndamediawiki/html/includes/specials/SpecialUpload.php(550): UploadFromFile->verifyUpload()
> #13 /var/www/ndamediawiki/html/includes/specials/SpecialUpload.php(244): SpecialUpload->processUpload()
> #14 /var/www/ndamediawiki/html/includes/specialpage/SpecialPage.php(647): SpecialUpload->execute()
> #15 /var/www/ndamediawiki/html/includes/specialpage/SpecialPageFactory.php(1366): SpecialPage->run()
> #16 /var/www/ndamediawiki/html/includes/MediaWiki.php(314): MediaWiki\SpecialPage\SpecialPageFactory->executePath()
> #17 /var/www/ndamediawiki/html/includes/MediaWiki.php(930): MediaWiki->performRequest()
> #18 /var/www/ndamediawiki/html/includes/MediaWiki.php(564): MediaWiki->main()
> #19 /var/www/ndamediawiki/html/index.php(53): MediaWiki->run()
> #20 /var/www/ndamediawiki/html/index.php(46): wfIndexMain()
> #21 {main}

**Comment by octfx** [comment]
Thanks for reporting!

This issue should be fixed in the latest develop commit :)

**Comment by cruxicheiros** [comment]
No problem! Thank you for fixing it :)

**Comment by alistair3149** [comment]
Seems to be fixed in v3.0.8, closing this now.
