### ISSUE TITLE
Deprecated php function alert

### ISSUE THREAD

**Issue by GenerationFallout** [StarCitizenWiki/mediawiki-extensions-EmbedVideo#21]
Hello,

This is not a bug report but rather a feedback on mediawiki 1.38 and 1.39 (WMF version): 

`642806#0: *1341817 FastCGI sent in stderr: "PHP message: PHP Deprecated: Use of ParserOutput::addModules with non-array argument was deprecated in MediaWiki 1.38. [Called from MediaWiki\Extension\EmbedVideo\EmbedVideoHooks::parseEV in [/httpdocs/extensions/EmbedVideo/includes/EmbedVideoHooks.php](https://XXX.XXX.XXX.XXX:8443/smb/file-manager/code-editor?currentDir=%2Fhttpdocs%2Fextensions%2FEmbedVideo%2Fincludes&subscriptionId=1&file=EmbedVideoHooks.php&redirect=%2Fsmb%2Flog-file%2Fbrowser%2Fid%2F1) at line 249] in [/includes/debug/MWDebug.php](https://212.227.190.175:8443/smb/file-manager/code-editor?currentDir=%2Fhttpdocs%2Fincludes%2Fdebug&subscriptionId=1&file=MWDebug.php&redirect=%2Fsmb%2Flog-file%2Fbrowser%2Fid%2F1) on line 377PHP message: PHP Deprecated: Use of ParserOutput::addModuleStyles with non-array argument was deprecated in MediaWiki 1.38. [Called from MediaWiki\Extension\EmbedVideo\EmbedVideoHooks::parseEV in [/httpdocs/extensions/EmbedVideo/includes/EmbedVideoHooks.php](https://212.227.190.175:8443/smb/file-manager/code-editor?currentDir=%2Fhttpdocs%2Fextensions%2FEmbedVideo%2Fincludes&subscriptionId=1&file=EmbedVideoHooks.php&redirect=%2Fsmb%2Flog-file%2Fbrowser%2Fid%2F1) at line 250] in [/includes/debug/MWDebug.php](https://XXX.XXX.XXX.XXX:8443/smb/file-manager/code-editor?currentDir=%2Fhttpdocs%2Fincludes%2Fdebug&subscriptionId=1&file=MWDebug.php&redirect=%2Fsmb%2Flog-file%2Fbrowser%2Fid%2F1) on line 377" while reading response header from upstream`

Sincerely,

Kims

**Comment by alistair3149** [comment]
Thanks for the report! It is now deprecated in 29c85ed. Closing this now.
