### ISSUE TITLE
Call to undefined method FSFile::getTitle() on mp3 file

### ISSUE THREAD

**Issue by Reception123** [StarCitizenWiki/mediawiki-extensions-EmbedVideo#22]
**Describe the bug**
Call to undefined method FSFile::getTitle() from /srv/mediawiki/w/extensions/EmbedVideo/includes/Media/FFProbe/FFProbe.php(68) #0 /srv/mediawiki/w/includes/libs/objectcache/wancache/WANObjectCache.php(1700): MediaWiki\\Extension\\EmbedVideo\\Media\\FFProbe\\FFProbe->MediaWiki\\Extension\\EmbedVideo\\Media\\FFProbe{closure}(boolean, integer, array, NULL, array) #1 /srv/mediawiki/w/includes/libs/objectcache/wancache/WANObjectCache.php(1532): WANObjectCache->fetchOrRegenerate(string, integer, Closure, array, array) #2 /srv/mediawiki/w/extensions/EmbedVideo/includes/Media/FFProbe/FFProbe.php(80): WANObjectCache->getWithSetCallback(string, integer, Closure) #3 /srv/mediawiki/w/extensions/EmbedVideo/includes/Media/FFProbe/FFProbe.php(104): MediaWiki\\Extension\\EmbedVideo\\Media\\FFProbe\\FFProbe->getMetaData(string) #4 /srv/mediawiki/w/extensions/EmbedVideo/includes/Media/AudioHandler.php(316): MediaWiki\\Extension\\EmbedVideo\\Media\\FFProbe\\FFProbe->getStream(string) #5 /srv/mediawiki/w/extensions/EmbedVideo/includes/Media/AudioHandler.php(273): MediaWiki\\Extension\\EmbedVideo\\Media\\AudioHandler->getFFProbeResult(FSFile) #6 /srv/mediawiki/w/includes/media/MediaHandler.php(236): MediaWiki\\Extension\\EmbedVideo\\Media\\AudioHandler->getMetadata(FSFile, string) #7 /srv/mediawiki/w/includes/utils/MWFileProps.php(88): MediaHandler->getSizeAndMetadataWithFallback(FSFile, string) #8 /srv/mediawiki/w/includes/upload/UploadBase.php(552): MWFileProps->getPropsFromPath(string, string) #9 /srv/mediawiki/w/includes/upload/UploadBase.php(485): UploadBase->verifyPartialFile() #10 /srv/mediawiki/w/includes/upload/UploadBase.php(391): UploadBase->verifyFile() #11 /srv/mediawiki/w/includes/upload/UploadFromFile.php(95): UploadBase->verifyUpload() #12 /srv/mediawiki/w/includes/api/ApiUpload.php(633): UploadFromFile->verifyUpload() #13 /srv/mediawiki/w/includes/api/ApiUpload.php(110): ApiUpload->verifyUpload() #14 /srv/mediawiki/w/includes/api/ApiMain.php(1874): ApiUpload->execute() #15 /srv/mediawiki/w/includes/api/ApiMain.php(853): ApiMain->executeAction() #16 /srv/mediawiki/w/includes/api/ApiMain.php(824): ApiMain->executeActionWithErrorHandling() #17 /srv/mediawiki/w/api.php(90): ApiMain->execute() #18 /srv/mediawiki/w/api.php(45): wfApiMain() #19 {main}Call to undefined method FSFile::getTitle()
from /srv/mediawiki/w/extensions/EmbedVideo/includes/Media/FFProbe/FFProbe.php(68)
#0 /srv/mediawiki/w/includes/libs/objectcache/wancache/WANObjectCache.php(1700): MediaWiki\Extension\EmbedVideo\Media\FFProbe\FFProbe->MediaWiki\Extension\EmbedVideo\Media\FFProbe{closure}(boolean, integer, array, NULL, array)
[#1 (closed)](https://github.com/hydrawiki/extensions/EmbedVideo/-/issues/1) /srv/mediawiki/w/includes/libs/objectcache/wancache/WANObjectCache.php(1532): WANObjectCache->fetchOrRegenerate(string, integer, Closure, array, array)
[#2 (closed)](https://github.com/hydrawiki/extensions/EmbedVideo/-/issues/2) /srv/mediawiki/w/extensions/EmbedVideo/includes/Media/FFProbe/FFProbe.php(80): WANObjectCache->getWithSetCallback(string, integer, Closure)
[#3 (closed)](https://github.com/hydrawiki/extensions/EmbedVideo/-/issues/3) /srv/mediawiki/w/extensions/EmbedVideo/includes/Media/FFProbe/FFProbe.php(104): MediaWiki\Extension\EmbedVideo\Media\FFProbe\FFProbe->getMetaData(string)
[#4 (closed)](https://github.com/hydrawiki/extensions/EmbedVideo/-/issues/4) /srv/mediawiki/w/extensions/EmbedVideo/includes/Media/AudioHandler.php(316): MediaWiki\Extension\EmbedVideo\Media\FFProbe\FFProbe->getStream(string)
[#5 (closed)](https://github.com/hydrawiki/extensions/EmbedVideo/-/issues/5) /srv/mediawiki/w/extensions/EmbedVideo/includes/Media/AudioHandler.php(273): MediaWiki\Extension\EmbedVideo\Media\AudioHandler->getFFProbeResult(FSFile)
[#6 (closed)](https://github.com/hydrawiki/extensions/EmbedVideo/-/issues/6) /srv/mediawiki/w/includes/media/MediaHandler.php(236): MediaWiki\Extension\EmbedVideo\Media\AudioHandler->getMetadata(FSFile, string)
[#7 (closed)](https://github.com/hydrawiki/extensions/EmbedVideo/-/issues/7) /srv/mediawiki/w/includes/utils/MWFileProps.php(88): MediaHandler->getSizeAndMetadataWithFallback(FSFile, string)
[#8 (closed)](https://github.com/hydrawiki/extensions/EmbedVideo/-/issues/8) /srv/mediawiki/w/includes/upload/UploadBase.php(552): MWFileProps->getPropsFromPath(string, string)
[#9 (closed)](https://github.com/hydrawiki/extensions/EmbedVideo/-/issues/9) /srv/mediawiki/w/includes/upload/UploadBase.php(485): UploadBase->verifyPartialFile()
[#10 (closed)](https://github.com/hydrawiki/extensions/EmbedVideo/-/issues/10) /srv/mediawiki/w/includes/upload/UploadBase.php(391): UploadBase->verifyFile()
[#11 (closed)](https://github.com/hydrawiki/extensions/EmbedVideo/-/issues/11) /srv/mediawiki/w/includes/upload/UploadFromFile.php(95): UploadBase->verifyUpload()
[#12 (closed)](https://github.com/hydrawiki/extensions/EmbedVideo/-/issues/12) /srv/mediawiki/w/includes/api/ApiUpload.php(633): UploadFromFile->verifyUpload()
[#13 (closed)](https://github.com/hydrawiki/extensions/EmbedVideo/-/issues/13) /srv/mediawiki/w/includes/api/ApiUpload.php(110): ApiUpload->verifyUpload()
#14 /srv/mediawiki/w/includes/api/ApiMain.php(1874): ApiUpload->execute()
[#15 (closed)](https://github.com/hydrawiki/extensions/EmbedVideo/-/issues/15) /srv/mediawiki/w/includes/api/ApiMain.php(853): ApiMain->executeAction()
[#16 (closed)](https://github.com/hydrawiki/extensions/EmbedVideo/-/issues/16) /srv/mediawiki/w/includes/api/ApiMain.php(824): ApiMain->executeActionWithErrorHandling()
[#17 (closed)](https://github.com/hydrawiki/extensions/EmbedVideo/-/issues/17) /srv/mediawiki/w/api.php(90): ApiMain->execute()
[#18 (closed)](https://github.com/hydrawiki/extensions/EmbedVideo/-/issues/18) /srv/mediawiki/w/api.php(45): wfApiMain()
[#19 (closed)](https://github.com/hydrawiki/extensions/EmbedVideo/-/issues/19) {main}
**To Reproduce**
Upload mp3 file
**Expected behavior**
Upload to work
**Screenshots**

**Technical information:**
MediaWiki 1.37.2 PHP 7.4

**Additional context**

**Comment by octfx** [comment]
This should be fixed in the develop branch, can you run a test?

**Comment by Reception123** [comment]
I assume https://github.com/StarCitizenWiki/mediawiki-extensions-EmbedVideo/commit/637cf1b4aa8ae6e386947009395eaa432014b42c is all that is needed for the test?

**Comment by octfx** [comment]
Yes

**Comment by Reception123** [comment]
@octfx Real sorry for the delay, yes indeed that fixes it. Thank you very much! I'll wait for it to go to the master branch :)

**Comment by alistair3149** [comment]
Merged into master branch with release v3.0.8
Closing this now.
