### ISSUE TITLE
Question: compatibility policy

### ISSUE THREAD

**Issue by JeroenDeDauw** [StarCitizenWiki/mediawiki-extensions-EmbedVideo#25]
I would like to use the extension with MW 37. It is however not clear what versions `master` is compatible with, and will maintain compatibility with. The tagged releases also do not have compatibility info.

Is the latest release compatible with MW 37? For how long will `master` remain compatible?

Enhancement request: add compat info to the readme and change history

**Comment by alistair3149** [comment]
At the moment the master branch is compatible to any version above 1.35. @octfx what's your plan on the minimum version?

**Comment by octfx** [comment]
This information is indeed lacking.
Realistically we are targeting LTS compatibility, meaning master will be compatible with current LTS.

Other than that, the code should work with any version above 1.35.

I'll / we'll be adding compatibility information from now on for each new release :)
