### ISSUE TITLE
packagist.org has not discovered release 3.0.8 yet

### ISSUE THREAD

**Issue by mdoggydog** [StarCitizenWiki/mediawiki-extensions-EmbedVideo#27]
**Describe the bug**
Release 3.0.8 has not appeared at packagist.org yet, preventing easy upgrades via `composer`.

**To Reproduce**
1. Browse https://packagist.org/packages/starcitizenwiki/embedvideo
2. Witness lack of v3.0.8

Perhaps v3.0.8 was tagged incorrectly somehow?  The auto-update does appear to still be in effect (e.g., `dev-master` looks up-to-date).

**Comment by octfx** [comment]
Thanks for the report!

I've re-released the tag, composer should be updated now,

**Comment by mdoggydog** [comment]
Yep, 3.0.8 is on packagist now, and `composer` has happily grabbed it.  Thanks!
