### ISSUE TITLE
Service request: Niconico

### ISSUE THREAD

**Issue by Fyren** [StarCitizenWiki/mediawiki-extensions-EmbedVideo#28]
Site: https://www.nicovideo.jp
Example non-embed URL: https://www.nicovideo.jp/watch/sm40807360
Example embed URL: https://embed.nicovideo.jp/watch/sm40807360

The IDs are always two letters followed by digits.

The original EV repo supports nicovideo.jp: 

```php
'nico' => [
            'embed'         => '<iframe title="%4$s" allowfullscreen="allowfullscreen" frameborder="0" width="%2$d" height="%3$d" src="https://embed.nicovideo.jp/watch/%1$s?oldScript=1&amp;allowProgrammaticFullScreen=1" style="max-width: 100%;"></iframe>',
            'default_width' => 640,
            'default_ratio' => 1.59609120521173, // (490 / 307)
            'https_enabled' => false,
            'url_regex'     => [
                '#nicovideo\.jp/watch/((?:[a-zA-Z]{2})?[\d]+)#is'
            ],
            'id_regex'      => [
                '#^((?:[a-zA-Z]{2})?[\d]+)$#is'
            ]
        ],
```

The HTML the site's own share button generates looks like this:

`<script type="application/javascript" src="https://embed.nicovideo.jp/watch/VIDEOID/script?w=WIDTH&h=HEIGHT"></script><noscript><a href="https://www.nicovideo.jp/watch/VIDEOID">VIDEO TITLE</a></noscript>`

And that script ends up inserting an iframe that looks like this:

`<iframe allowfullscreen="allowfullscreen" allow="autoplay" src="https://embed.nicovideo.jp/watch/VIDEOID?persistence=1&oldScript=1&referer=REFERRINGURL&from=0&allowProgrammaticFullScreen=1" style="max-width: 100%;" width="WIDTH" height="HEIGHT" frameborder="0"></iframe>`

I could not find documentation about embeds on their site, so I can't tell you what their parameters do.

**Comment by octfx** [comment]
Should be implemented in current develop branch. Could you run a test?

**Comment by Fyren** [comment]
It does appear to work for me.  Thanks.
