### ISSUE TITLE
Embed Service Request: Bilibili

### ISSUE THREAD

**Issue by vexx32** [StarCitizenWiki/mediawiki-extensions-EmbedVideo#29]
**Service Name**
Bilibili

**URL to an example embed**
https://bilibili.com/BV1Hz4y1k7ae

Page with embedded video: https://noita.fandom.com/zh/wiki/Template:BilibiliVideo

**Additional notes**
Currently the only way this seems to be done is with javascript (this is how it's done in the above page), using this script: https://dev.fandom.com/wiki/MediaWiki:BilibiliVideo.js

Not sure if they have developer documentation available, I've not been able to find any at the moment. The final iframe inserted looks like this:
```html
<iframe class="bili-show bilibili-iframe" id="bv-1Hz4y1k7ae" src="//player.bilibili.com/player.html?bvid=1Hz4y1k7ae&amp;page=1" scrolling="no" border="0" frameborder="no" framespacing="0" allowfullscreen="true" style="width: 90%; height: 535.946px;"></iframe>
```

**Comment by octfx** [comment]
Implemented in latest develop :)

**Comment by vexx32** [comment]
Thanks! 💖
