### ISSUE TITLE
More information on consent overlay

### ISSUE THREAD

**Issue by alistair3149** [StarCitizenWiki/mediawiki-extensions-EmbedVideo#30]
Current issues:
- User doesn't know what platform is the video from until the embed is loaded
- Other than loading the video, user don't know it is a consent button

Potential solutions:
- Display which platform it is from (e.g. plain text, logo, etc.)
- Maybe link to the privacy policy page of that platform?
- Tooltip message on the load button that informs about the consent part

It's just some rough ideas currently since providers treat users' data differently, with some platforms being more questionable. I can work on the visual side if needed, probably put up a wireframe later.

**Comment by octfx** [comment]
I like that idea!
How about something like this:
![image](https://user-images.githubusercontent.com/6594492/195999886-e0f694f9-c2c1-4b66-9ddb-a36b72f8ea68.png)

If explicit consent is active:
- The service name is displayed in the button
- And if a privacy policy is set for the service, a link is added to the bottom right corner

**Comment by alistair3149** [comment]
> I like that idea! How about something like this: ![image](https://user-images.githubusercontent.com/6594492/195999886-e0f694f9-c2c1-4b66-9ddb-a36b72f8ea68.png)
> 
> If explicit consent is active:
> 
> * The service name is displayed in the button
> * And if a privacy policy is set for the service, a link is added to the bottom right corner

Yeah I'm thinking something similar too.

Privacy policy under button, platform on top right:
![example~2](https://user-images.githubusercontent.com/9260542/196000624-69c33708-0482-46dc-a0f8-193bcdd102a5.png)

Popup tooltip when hover on the load button, can contain privacy policy link and also a little blurb on consent
![example~3](https://user-images.githubusercontent.com/9260542/196000626-5b9b5e29-2fab-4017-bc75-868b5d7c1db8.png)

**Comment by octfx** [comment]
As always, a nicer design from your side 😋

One thing that comes to mind, what about mobile devices and hovering? 
Change the default "click to load" to "click to show privacy, click again to load"?

**Comment by alistair3149** [comment]
Thanks for creating a branch and working on it!

Yes you're right, mobile is trickier since there are way less space for UI, plus we also don't have control over the dimensions of the embed (e.g. embed into a infobox template so the dimension is super small). Because of that I think it is best to avoid putting more information on the initial overlay.

I took out the hover idea since it would not work on mobile and on desktop it is a way to see the full thumbnail (as sometimes overlay will cover some parts of it).

Here's a rough flow:
![Group 4](https://user-images.githubusercontent.com/9260542/196049283-53df2bbd-c4d5-4259-a243-e7676a5831d2.jpg)

**Comment by octfx** [comment]
Current iteration:
https://user-images.githubusercontent.com/6594492/196055287-7cdaf1f7-f9da-4f2d-8cd3-195e45ebcf93.mp4

The privacy notice is a separate div containing the elements, hidden per default.
If the privacy page is enabled in the configuration, clicking the `load content` button show the div, when clicking `dismiss` the div is hidden and the original `click to load` div is shown.

Clicking `continue` loads the iframe content.

The JS and CSS may need some refactoring

**Comment by alistair3149** [comment]
Looks great! I will look into the styles and scripts later

**Comment by octfx** [comment]
Closing as the feature was implemented :)
