### ISSUE TITLE
Button is not clickable when DarkMode is on

### ISSUE THREAD

**Issue by lens0021** [StarCitizenWiki/mediawiki-extensions-EmbedVideo#39]
**Describe the bug**

The 'Load video' button is not focusable when DarkMode is on.

**To Reproduce**
1. Install EmbedVideo and DarkMode(https://www.mediawiki.org/wiki/Extension:DarkMode)
2. Create a page with an embeded video.
3. Turn on the dark mode
4. Try to click the 'Load video' button.

**Expected behavior**
The video should be loaded.

**Screenshots**
[Screencast from 2023-01-09 22-59-08.webm](https://user-images.githubusercontent.com/28209361/211325161-c8afeeba-4289-40d0-a224-8bf37f060885.webm)

**Technical information:**
 - OS: Fedora 37
 - Browser: FireFox 108.0.1
 - Extension Version: 3.1.0 (4f645dd) 20:36, 21 November 2022
 - MediaWiki Version: [1.39.1](https://www.mediawiki.org/wiki/MediaWiki_1.39) [(8c5996d)](https://gerrit.wikimedia.org/g/mediawiki/core/+/8c5996d3f06b7e7b5caa79e7fbab7e648cdace27) 02:20, 7 January 2023

**Additional context**
Setting the z-index to `1` solves this, but maybe there is a nicer solution.

**Comment by octfx** [comment]
@alistair3149 may you have a look at this?

**Comment by alistair3149** [comment]
Do you have a live page with the issue?

**Comment by lens0021** [comment]
> Do you have a live page with the issue?

https://femiwiki.com/index.php?oldid=299612&uselang=en#%EC%98%81%EC%83%81 was, but I [have applied MediaWiki:Common.css](https://femiwiki.com/w/Special:diff/301374) for it.

**Comment by alistair3149** [comment]
Okay found the issue.
Dark mode applies `filter` to the `<img>` element within EmbedVideo, which changed the stacking order of the DOM elements.
It should be an upstream issue but we will also apply a fix on our end.

**Comment by alistair3149** [comment]
Would you mind to check if the fix works for you?

**Comment by lens0021** [comment]
The patch works for my local MediaWiki instance. I am sorry I cannot test it on https://femiwiki.com because it is not my own wiki, but my team's. The release pipeline is little long to test.

**Comment by alistair3149** [comment]
No worries. Thanks for verifying it! Closing the issue now.
