### ISSUE TITLE
"EmbedVideo was given an illegal value for the alignment parameter "inline". Valid values are "left", "center", "right", or "inline"."

### ISSUE THREAD

**Issue by Hb1290** [StarCitizenWiki/mediawiki-extensions-EmbedVideo#45]
We have been seeing the above error on most if not all embeds on our wiki (AVID) about the last day. Given the timing, I believe it may be connected to this commit: https://github.com/StarCitizenWiki/mediawiki-extensions-EmbedVideo/commit/87a3a46897a81767a88ceba2c2c803d810822dab

Example link below: 
https://avid.miraheze.org/wiki/Walt_Disney_Pictures#Videos-1

**Comment by octfx** [comment]
This was changed in this commit: https://github.com/StarCitizenWiki/mediawiki-extensions-EmbedVideo/commit/1466c0b8bcf91000d78349368f8b27fb281f5a32#diff-49081cdb191878a51c5dee1da560a0359039116b14f5709085405b6580c8ae27L405

But I do not see why @alistair3149 do you know why `inline` was changed to `none`?

**Comment by alistair3149** [comment]
> This was changed in this commit: [1466c0b#diff-49081cdb191878a51c5dee1da560a0359039116b14f5709085405b6580c8ae27L405](https://github.com/StarCitizenWiki/mediawiki-extensions-EmbedVideo/commit/1466c0b8bcf91000d78349368f8b27fb281f5a32#diff-49081cdb191878a51c5dee1da560a0359039116b14f5709085405b6580c8ae27L405)
> 
> But I do not see why @alistair3149 do you know why `inline` was changed to `none`?

It is changed to `none` to align the `alignment` attribute with the [default MediaWiki image syntax](https://mediawiki.org/wiki/Help:Images). `inline` is the default state and it was missing the `none` parameter before.

As for the issue itself, I don't see the `inline` parameter being applied in the wikitext. Is it a default when the YouTube tag is used?

**Comment by octfx** [comment]
It is set through Template: YouTube
Do we just add it back to the list of allowed params? Or do we ignore this specific value?

**Comment by alistair3149** [comment]
> It is set through Template: YouTube Do we just add it back to the list of allowed params? Or do we ignore this specific value?

I think we can just ignore the specific value for backward compatibility. The `inline` value is the only one that doesn't align with MW default in terms of alignments

**Comment by alistair3149** [comment]
The patch should be up in 3.2.5, closing this now.
