### ISSUE TITLE
When iframe loads it has attribute display:none

### ISSUE THREAD

**Issue by ruvilonix** [StarCitizenWiki/mediawiki-extensions-EmbedVideo#48]
Since the update to 3.25, on many pages, when the user clicks "Load video", the iframe is added to the DOM, but when inspecting with browser, its display is set to 'none', and the video is not visible, but the audio can be heard. Example here: https://comprehensibleinputwiki.org/wiki/User:Dimpizzy/Sandbox

I'm not sure why it's working on some [pages](https://comprehensibleinputwiki.org/wiki/Ukrainian/Library) and not others.

**Comment by alistair3149** [comment]
It looks like that it could be caching issue on your site, since the CSS is no longer in the current version of EmbedVideo.

**Comment by ruvilonix** [comment]
Oh, sorry! I completely forgot I had custom CSS to hide the iframe at first to make it load faster.
