### ISSUE TITLE
/i18n/de.json (additional) translated strings are ignored?

### ISSUE THREAD

**Issue by SanneSideUp** [StarCitizenWiki/mediawiki-extensions-EmbedVideo#49]
Hiya,
and thank you for keeping this extension alive.

I use a Mediawiki version 1.35.6 with a German GUI Custom Skin derived from the DarkVector skin on PHP 7.4.33 and this Fork Version 3.2.1. I noticed that the de.json file in i18n/ was missing a lot of entries compared to the en.json and that some quotation marks weren't escaped correctly compared to the en.json. 
So, I fixed that on my server installation for testing purposes, but it looks like the translation strings from de.json are not used anyway?

For example, if you check the embedded YouTube Video [here](https://spookyverse.de/wiki/Kim_Manners#Notizen)
- It says "Load video" on the thumbnail (should be Video laden, in en .json "`embedvideo-load":`)
- if you click on "Load video" (a button)  you get a mix of English and German  "YouTube might collect personal data" (in en.json `"embedvideo-consent-privacy-notice-text":`
"Datenschutzrichilinie" (a Link to https://www.youtube.com/howyoutubeworks/user-settings/privacy/, all good, shows up in German for me)
then two buttons
Fortfahren   Ausblenden" (all three German strings for Datenschrutzrichtlinie, Fortfahren und Ausblenden were present in the packaged de.json file as
```
	"embedvideo-consent-privacy-policy": "Datenschutzrichtlinie",
	"embedvideo-consent-privacy-notice-continue": "Fortfahren",
	"embedvideo-consent-privacy-notice-dismiss": "Ausblenden",
```
If I change one of these translations in my live de.json it also has no effect. Hence, why I think the translations are not used from the de.json but somewhere else.

**Expected behavior**
Since I added at least the following two entries my de.json on the server, I would expect that strings are now display in German on my German GUI wiki:
`"embedvideo-consent-privacy-notice-text": "$1 könnte persönliche Daten sammeln.",` (instead of "$1 {which was parsed correctly as service YouTube] might collect personal data" where $1 is a variable.
`"embedvideo-load": "Video $1 laden",`  (instead of "Load video") 

If I delete my en.json on my live version, EN strings are still displayed. Which is odd, would have expected an error, unless there is hard coded fall back to EN? 
Also, I wonder what the purpose of EmbedVideo.i18n.magic.php is? It only contains a declaration `$magicWords['en'] = `

**Technical information:**
 - Windows 10
 - Chrome
 - 3.2.1
 - MediaWiki Version 1.35.6 with a custom skin Derived from DarkVector
 - Host type:  shared hosting

I would be happy to provide my extended de.json if that would be helpful for other German users and the translated strings are displayed correctly:-)

**Comment by octfx** [comment]
Hi @SanneSideUp, thank you _very_ much for this detailed report!

I've just updated all german translations based on `en.json`. Would you be able to test the changes present in the current develop branch?

**Comment by SanneSideUp** [comment]
It just noticed it might be my custom Vector skin causing this. On the mobile skin (which uses the MinervaNeue skin)  the translations show up. Behaviour with translations not displaying is reproducible with mediawikis default VectorSkin as well, my custom skin is based on as well the Timless Skin and MonoBook Skin. Odd.

**Comment by SanneSideUp** [comment]
Hi @octfx 
Thank for the super fast reply. Just updated to [EmbedVideo 3.2.5](https://spookyverse.de/wiki/Spezial:Version). Sadly, no change in displaying the translation. 
Also, the video thumbnail is no longer displayed nor the video is loaded on clicking Load in any of the Skins' desktop versions (unless this is a server caching issue which as a shared user hosting can't do much about). 

What's also odd: In the MinerveNeue Desktop Skin display the translation were also missing, in the MinervaNeue mobile skin view the translations are there. So maybe more an issue how the Desktop skins call the translations files/render them in the output?

**Comment by octfx** [comment]
I am closing this for now, as Release v3.2.6 seems to successfully load german translations.
You can see an example here: https://star-citizen.wiki/Vulture_(Raumschiff)

If you still have an issue feel free to re-open this :)
