### ISSUE TITLE
 Thumbnails not centered in tables

### ISSUE THREAD

**Issue by GenerationFallout** [StarCitizenWiki/mediawiki-extensions-EmbedVideo#5]
Hello !

First, thank you for taking over this abandoned extension :)

We encounter on our wiki a problem for the minuatures which are not centered in the tables :

For example : https://fallout-wiki.com/Fins_de_Fallout_3

![image](https://user-images.githubusercontent.com/68496923/120634721-dfc97a00-c46b-11eb-9d4b-47f625a7ba00.png)

Thank you for your work !

**Comment by octfx** [comment]
Thanks for the report!

The issue seems to stem from Vector, centering all entries in a table.
I've added a fix that left aligns all thumbnails, it should be fixed in the latest develop branch

**Comment by GenerationFallout** [comment]
Fixed :)
