### ISSUE TITLE
Local videos should play once wgEmbedVideoUseEmbedStyleForLocalVideos is enabled

### ISSUE THREAD

**Issue by kghbln** [StarCitizenWiki/mediawiki-extensions-EmbedVideo#56]
**Issue**
After setting ...
```php
$wgEmbedVideoUseEmbedStyleForLocalVideos = true;
```
... I can use the `description` and `title` parameters to embed locally uploaded files. However, the video no longer plays. I get an "embedvideo-service-fauxembedservice". See the screenshot.

Syntax used:
```
[[File:Big Buck Bunny 360 10s 30MB 0.mp4|560px|description=This is the description|title=Big Buck Bunny]]
```

**Error**
```
Warning: Undefined array key "autoresize" in /../EmbedVideo/includes/Media/TransformOutput/VideoEmbedTransformOutput.php on line 
```

**Setup**
Product | Version
-- | --
MediaWiki | 1.39.2 (0688e68)
PHP | 8.0.28 (apache2handler)
MariaDB | 10.5.17-MariaDB-1:10.5.17+maria~ubu2004
ICU | 67.1
EmbedVideo | 3.2.5 (0dbdd9a)

**Screenshot**
![grafik](https://github.com/StarCitizenWiki/mediawiki-extensions-EmbedVideo/assets/1104078/915083ba-7976-42c3-ad10-b0ff5b798d7e)

**Comment by octfx** [comment]
The local embed styling support broke with the html refactor.
I hadn't had the time to fix this yet, but I'll bump it up my list!

**Comment by octfx** [comment]
This is the current working state from develop on MW 1.39
https://github.com/StarCitizenWiki/mediawiki-extensions-EmbedVideo/assets/6594492/a9e58154-5ce1-4d88-93ef-78635c0ba25d

**Comment by kghbln** [comment]
Works nicely on MW 1.35.x. I cannot test on MW 1.39.x though. Assuming this works, too. Thanks a lot!!!
