### ISSUE TITLE
Local videos should resize beyond 640px when embedded

### ISSUE THREAD

**Issue by kghbln** [StarCitizenWiki/mediawiki-extensions-EmbedVideo#57]
**Setup**
Product | Version
-- | --
MediaWiki | 1.35.10 (5fb802c)17:42, 8 May 2023
PHP | 7.4.3-4ubuntu2.18 (apache2handler)
MariaDB | 10.3.38-MariaDB-0ubuntu0.20.04.1
EmbedVideo | 3.2.5 (0dbdd9a) 20:25, 13 February 2023

**LocalSettings.php**
```php
$wgEmbedVideoDefaultWidth = 1280;
```
I am unsure if this setting is even meant to be used with local files. From the docu and "extension.json", I cannot tell.

**Issue**
Using the `[[File:MyVideo.mp4|1280px]]` syntax does not work. The files are added with 640px most of the time sometimes even with 320px only.

**Comment by kghbln** [comment]
Another question somewhat related: Is the syntax [[File:MyVideo.mp4|1280x360px]] supported for local files?

**Comment by octfx** [comment]
Current develop should address this:
![image](https://github.com/StarCitizenWiki/mediawiki-extensions-EmbedVideo/assets/6594492/3d2af820-6a57-407e-98f5-e392c50aaeaa)

The mediawiki image sizing syntax should work for local files aswell

**Comment by octfx** [comment]
Should be fixed in v3.2.7
