### ISSUE TITLE
error 500

### ISSUE THREAD

**Issue by okach666** [StarCitizenWiki/mediawiki-extensions-EmbedVideo#58]
**Describe the bug**
expansion crashes the wiki. Error 500

**To Reproduce**
1. copy EmbedVideo to extension directory 
2. add wfLoadExtension( 'EmbedVideo' ); to LocalSettings.php
3. See error

**Screenshots**
https://prnt.sc/RFx3fn6b9NK_  - LocalSettings.php
https://prnt.sc/a_lpZgs4GvF0   - Browser 

**Technical information:**
 - OS: debian
 - Browser Firefox 113.0.
 - Extension Version 2.3.6
 - MediaWiki | 1.39.3
 - PHP | 8.2.6 (apache2handler)
 - MariaDB | 10.3.38-MariaDB-0+deb10u1
 - ICU | 65.1
 - Pygments | 2.11.2

**Comment by octfx** [comment]
Do you have access to the apache logs?
If so, could you provide those logs containing possible exceptions?

**Comment by okach666** [comment]
[Tue May 30 10:49:40.070914 2023] [php:error] [pid 1794] [client 10.80.34.28:38328] PHP Fatal error:  Uncaught ExtensionDependencyError: EmbedVideo requires curl PHP extension to be installed.\n in /var/www/wiki/includes/registration/ExtensionRegistry.php:432\nStack trace:\n#0 /var/www/wiki/includes/registration/ExtensionRegistry.php(276): ExtensionRegistry->readFromQueue()\n#1 /var/www/wiki/includes/Setup.php(278): ExtensionRegistry->loadFromQueue()\n#2 /var/www/wiki/includes/WebStart.php(86): require_once('...')\n#3 /var/www/wiki/index.php(44): require('...')\n#4 {main}\n  thrown in /var/www/wiki/includes/registration/ExtensionRegistry.php on line 432

**Comment by octfx** [comment]
You need to install the php-curl extension to fix this error
