### ISSUE TITLE
Embed Service Request: direct video files

### ISSUE THREAD

**Issue by Tuphal** [StarCitizenWiki/mediawiki-extensions-EmbedVideo#60]
**Service Name**
Direct video files, for example local Sharepoint

**URL to an example embed**
https://SUBDOMAIN.sharepoint.com/:v:/r/sites/FOLDERSTRUCTURE/VIDEO.mp4

**Additional notes**
One can use the Widet:Video here https://www.mediawikiwidgets.org/Video

One extention for all videos would be great and easier to maintain and having only one format for all.

**Comment by Tuphal** [comment]
I had to change the regex in `protected function getUrlRegex()` in SharePoint.php
old: `'#^(https://[\w-]+.sharepoint.com/sites/.+\.\w+)$#is',`
new: `'#^(https://[\w-]+.sharepoint.com/.+\w+)$#is',`


I tested some variations:   
   
1. Direct link to mp4-file 
Does not work: Connection refused. Might be also a config-issue on SharePoint.
`{{#ev:sharepoint|https://__SUB__.sharepoint.com/:v:/r/sites/__PATH__/KnowHow/Video%20Introduction.mp4}}`
![image](https://github.com/StarCitizenWiki/mediawiki-extensions-EmbedVideo/assets/42291781/84814c28-b021-4be6-a152-543d62f02926)

   
   
2. Copy link as sharepoint Stream URL
Working with all additional options and views.
`{{#ev:sharepoint|https://__SUB__.sharepoint.com/sites/__PATH__/_layouts/15/stream.aspx?id=%2Fsites%2F__PATH__%2FKnowHow%2FVideo%20Introduction%2Emp4&referrer=SharePoint%2Eweb&referrerScenario=OpenDocLib%2Eview}}`
![image](https://github.com/StarCitizenWiki/mediawiki-extensions-EmbedVideo/assets/42291781/7aba62e9-e397-4e1b-9095-155769792f26)

   
   
3. Use link from Stream-Page from Embedded code
Best and intended result. When having the mp4 in SharePoint, open the file in "Stream", click "Share" and use "Embedded code". Use the URL from this code snippet
`{{#ev:sharepoint|https://__SUB__.sharepoint.com/sites/__PATH__/_layouts/15/embed.aspx?UniqueId=a7665773-ec36-4351-ae2f-12ac9e124fba&embed=%7B%22ust%22%3Atrue%7D&referrer=StreamWebApp&referrerScenario=EmbedDialog.Create}}`
![image](https://github.com/StarCitizenWiki/mediawiki-extensions-EmbedVideo/assets/42291781/28ab2b91-6048-4867-97ef-c172bb46f503)

**Comment by Tuphal** [comment]
When using the link from the embedded code, the `getUrlRegex` doesn't have to be changed.

For this, we just need to document how to use it:

Example code-snippet:
`{{#ev:sharepoint|https://__SUB__.sharepoint.com/sites/__PATH__/_layouts/15/embed.aspx?UniqueId=a7w4ret4567xxa&embed=%7B%22ust%22%3Atrue%7D&referrer=StreamWebApp&referrerScenario=EmbedDialog.Create|480|right|Video Introduction}}`

Link to Video: Right-click on the video file in SharePoint -> open the file in "Stream" -> click the red "Share" button on the top right -> select "Embedded code" -> use the "src"-URL from the code snippet

**Comment by thomas-oneill** [comment]
Now that Microsoft has moved away from Stream, has any work been done to allow SharePoint videos again to be embedded?
