### ISSUE TITLE
Add Dailymotion to list of supported services

### ISSUE THREAD

**Issue by PChandonnay** [StarCitizenWiki/mediawiki-extensions-EmbedVideo#62]
Dailymotion (French equivalent to YouTube)

Example video: https://www.dailymotion.com/video/xu50vh

This service runs fine on the deprecated EmbedVideo extension: https://wiki.halo.fr/Halo_4_:_Forward_Unto_Dawn#.C3.89pisodes

**Comment by octfx** [comment]
Dailymotion was implemented in 1b1323068a54e65a6a6f9a041b2d366b45150ef2 and should work in the development branch

**Comment by octfx** [comment]
Information added to the readme and released in v3.2.8
