### ISSUE TITLE
Allow embedding videos specified in wgAllowExternalImagesFrom

### ISSUE THREAD

**Issue by Zwelf** [StarCitizenWiki/mediawiki-extensions-EmbedVideo#63]
I'd like to embed videos from a website that I control. For images I use https://www.mediawiki.org/wiki/Manual:$wgAllowExternalImagesFrom. Could the embed-video extension also allow embedding raw video files (e.g. mp4/webm files) from sites listed in this variable? 

https://www.mediawiki.org/wiki/Manual:$wgAllowExternalImagesFrom

## Detailed Description
Parse the same variable ($wgAllowExternalImagesFrom) either a string or a list of strings. And then allow embedding videos by just putting the link to the video in the source. `https://example.com/example.mp4`. Or by specifying the external video in `[[File:https://example.com/example.mp4|400px|right]]` or similar.

## Context
* Why is this change important to you? How would you use it?
The website is a chat archive and using videos uploaded there in the wiki would simplify the process of gathering new information
* How can it benefit other users?
It could simplify add new hosts that host raw video files.

**Comment by octfx** [comment]
I've added a new `external` service that should allow embedding external links.  
Ex:  `{{#ev:external|https://<domain>/<path-to-file>.<ext>}}`

Would you be able to test the changes from the develop branch?

**Comment by edg-l** [comment]
mediawiki 1.40.0
```
Warning: Undefined property: MediaWiki\Extension\EmbedVideo\EmbedService\ExternalVideo::$properties in /var/www/html/extensions/EmbedVideo/includes/EmbedService/ExternalVideo.php on line 94

Warning: Trying to access array offset on value of type null in /var/www/html/extensions/EmbedVideo/includes/Media/TransformOutput/AudioTransformOutput.php on line 40

Warning: Trying to access array offset on value of type null in /var/www/html/extensions/EmbedVideo/includes/Media/TransformOutput/VideoTransformOutput.php on line 69
```

also got #64

**Comment by edg-l** [comment]
The embed works but i get a warning sitewide:

```
Warning: Error: invalid magic word 'evu' [Called from MediaWiki\Extension\EmbedVideo\EmbedVideoHooks::onParserFirstCallInit in /var/www/html/extensions/EmbedVideo/includes/EmbedVideoHooks.php at line 126] in /var/www/html/includes/debug/MWDebug.php on line 508
```
