### ISSUE TITLE
Trailing whitespace in message "embedvideo-service-externalvidel

### ISSUE THREAD

**Issue by Nikerabbit** [StarCitizenWiki/mediawiki-extensions-EmbedVideo#67]
**Describe the bug**
Trailing whitespace is not supported in messages. 9a35f63f816fe7cc53875c1dfe46093f5e4b414a introduced such message.

**To Reproduce**
1. Look at any translation for this message coming from translatewiki.net. They don't have a trailing space.

**Expected behavior**
No trailing space.

**Screenshots**

**Technical information:**
 - Extension Version [e.g. 22]
 - MediaWiki Version [e.g. 1.35.0]
 - Host type [e.g. shared hosting]

**Additional context**

Could you also include this repository in https://github.com/MWStake/nonwmf-extensions so that it's searchable in https://codesearch.wmcloud.org/?

**Comment by octfx** [comment]
Thanks for the report!

Both the whitespace issue as well as the codesearch PR have been addressed! :)
