### ISSUE TITLE
Re-add vplayer and vlink support

### ISSUE THREAD

**Issue by Suraf** [StarCitizenWiki/mediawiki-extensions-EmbedVideo#69]
Originally back in Gamepedia the VideoLink extension support was merged into one new extension known as "EmbedVideo" which kept the backwards compatibility for "vplayer" and "vlink" but introduced new tags.

More information:
* https://www.mediawiki.org/wiki/Extension:EmbedVideo#Support_for_VideoLink_tags
* https://warcraft.wiki.gg/wiki/Help:VideoLink

However with the EmbedVideo fork, this functionality was lost and the only way to add videos to a wiki is by embedding it instead of linking it. Since Wowpedia forked over to wiki.gg (as Warcraft Wiki), we're using the EmbedVideo fork and without some similar tag here for vplayer and vlink/evl, some articles will be a bit of a bloated mess with videos.

Some examples:
* https://warcraft.wiki.gg/wiki/Warbringers vs https://wowpedia.fandom.com/wiki/Warbringers
* https://warcraft.wiki.gg/wiki/Dragonflight_in-game_cinematics vs https://wowpedia.fandom.com/wiki/Dragonflight_in-game_cinematics

Screenshots of how it looked:
![image](https://github.com/StarCitizenWiki/mediawiki-extensions-EmbedVideo/assets/19893933/c75aeeac-5b2f-4628-a586-1f49ce286cc9)
![image](https://github.com/StarCitizenWiki/mediawiki-extensions-EmbedVideo/assets/19893933/73b0801f-28a0-443a-8ab7-0405e4b18a3f)

Clicking a video link loads the video at the vplayer tag:
![image](https://github.com/StarCitizenWiki/mediawiki-extensions-EmbedVideo/assets/19893933/03000e01-5421-432d-9dfa-2aeda51667f6)

## Context
Warcraft Wiki (formerly Wowpedia) uses this nearly everywhere on the site and would love if this functionality came back with the forked version.

It can be a benefit to just linking multiple videos on a article instead of bloating the page with embed videos, especially with a large amount of videos.

## Possible Implementation
* Reintroduce the vplayer or evlplayer tag which will display the video (and switch to new ones) as a user clicks the video links.
* Reintroduce {{#vlink:}} or {{#evl}} for the links.

**Comment by octfx** [comment]
Thank you for this thorough feature request!
I'm open to implementing this, but will have to see when I've got the time.

Are there any features that could be dropped? E.g. supporting multiple `<vplayer/>` tags on a single page?

**Comment by Suraf** [comment]
> Thank you for this thorough feature request! I'm open to implementing this, but will have to see when I've got the time.
> 
> Are there any features that could be dropped? E.g. supporting multiple `<vplayer/>` tags on a single page?

Usually there was only ever one <vplayer /> on a single given page. IIRC if there were multiple - the first one would've been used regardless and the others completely ignored. Don't see much for allowing multiple of those tags anyways.

**Comment by octfx** [comment]
Develop now contains the initial work for `{{#evl}} / <vplayer/>`.
The current implementation adds the required iframe configuration to each video link element. Upon clicking a link, the config for the targeted video player is replaced. This works for videos that require consent through `$wgEmbedVideoRequireConsent` as well as for sites that just display the raw `<iframe>` embed.

Implemented:
- Video loading through `{{#evl}}`
- Usage of multiple `<vplayer />` elements with different ids
- Loading of different services in a single `<vplayer/>` by specifying the `service=` attribute on the link

TODO:
- Decide how to handle `<vplayer/>` elements without a `defaultid` (Currently a video container with a 'load video' button is shown that does nothing)

Currently not implemented:
- `style` attribute on `<vplayer/>`
- Unit- / Integrationtests
- Checks if `<vplayer/>` hooks are already registered with the parser
- Video lists in `evl` (+ `video to play` attribute)
- `default content` in `<vplayer/>` tag
