### ISSUE TITLE
PHP Deprecated

### ISSUE THREAD

**Issue by GenerationFallout** [StarCitizenWiki/mediawiki-extensions-EmbedVideo#7]
One of the php scripts no longer seems to be supported by the latest versions (7.4 and above ...).
This manages an error when executing a php script in ssh.

```
PHP Deprecated:  Premature access to service container [Called from MediaWiki\Extension\EmbedVideo\
mbedVideoHooks::onExtension in Mediawiki/extensions/EmbedVideo/incl
des/EmbedVideoHooks.php at line 69] in Mediawiki/includes/debug/MWD
bug.php on line 376
```

**Comment by octfx** [comment]
I'll have a later this later
Are you on Mediawiki version 1.36?

**Comment by GenerationFallout** [comment]
Yes, we are using version 1.36 :)

**Comment by octfx** [comment]
Current 3.0.2 release on master should fix this issue, could you test this? :)

**Comment by GenerationFallout** [comment]
Yes, It's good for us !
