### ISSUE TITLE
OGV files are never detected as video/ogg

### ISSUE THREAD

**Issue by pcjcos** [StarCitizenWiki/mediawiki-extensions-EmbedVideo#70]
**Describe the bug**
MimeAnalyzer never detects OGG Video files as video/ogg - related ticket at https://phabricator.wikimedia.org/T349458

Thus all .ogv video files [are embedded as audio files](https://github.com/StarCitizenWiki/mediawiki-extensions-EmbedVideo/blob/b2bbbb6b9ac128457a40aee736a5bd2aec3e6404/includes/EmbedVideoHooks.php#L69) and not video. Should probably use more than the mime type for OGG files.

**To Reproduce**
1. Upload an OGV file
2. Try to embed it (or just look at the preview) - it's detected as application/ogg and embeds as audio

**Expected behavior**
OGG video files should embed as videos

**Comment by octfx** [comment]
Thanks for the report!
I (currently) think it is best to wait for an upstream fix, and then update the mime type assignments in EmbedVideo accordingly.

On another note, [Chrome intends to drop the support for Theora ](https://groups.google.com/a/chromium.org/g/blink-dev/c/qqDdLkeyk7Y/m/ajHePzglAwAJ?pli=1)(ogg/ogv) entirely in early 2024..
