### ISSUE TITLE
Consent overlay: Add a direct link to the video

### ISSUE THREAD

**Issue by alex4401** [StarCitizenWiki/mediawiki-extensions-EmbedVideo#71]
The consent overlay should have a button leading to the embedded media in a new tab as an alternative choice.

## Detailed Description
As above. This has been requested in ARK Wiki's Discord server.

## Context
This may be useful for users who might not want to load the iframe directly on wiki in case they fear information may leak. Quoting the requester directly:

> The embedded YouTube videos (e.g. on https://ark.wiki.gg/wiki/Fishing_Rod) have no link to the video on YouTube. I'm not one to consent to them tracking my usage of the wiki, but I would like a link so I can view it directly on YouTube when I choose to.

## Possible Implementation
I can see two ways of implementing this:
* A "New tab" button on the second consent overlay, which already links to the service's privacy policy. This may have poor discoverability though.
![image](https://github.com/StarCitizenWiki/mediawiki-extensions-EmbedVideo/assets/33527044/b970b78e-865e-4834-85bb-ab1dfb6f2265)
* A button in the first stage footer. It would have to persist on hover. Perhaps labelled "Direct link"?
Normal: ![image](https://github.com/StarCitizenWiki/mediawiki-extensions-EmbedVideo/assets/33527044/3f022fbe-27b9-437a-98b0-82bcc9839639)
Hover:
![image](https://github.com/StarCitizenWiki/mediawiki-extensions-EmbedVideo/assets/33527044/472a49a1-bbbb-4e0c-96e8-e2c68cda7e43)

**Comment by octfx** [comment]
This too is now implemented in develop.  
The implementation is based on youtube, by directly linking the title

Embed: 
![image](https://github.com/StarCitizenWiki/mediawiki-extensions-EmbedVideo/assets/6594492/8417d915-fe23-488d-b1be-ddb1bd820f77)
Hover:
![image](https://github.com/StarCitizenWiki/mediawiki-extensions-EmbedVideo/assets/6594492/15e26df4-2e8f-45f0-9624-a9c38981d228)

**Comment by alex4401** [comment]
Thank you!
