### ISSUE TITLE
vplayer / evlplayer displays big block if no id is provided by default

### ISSUE THREAD

**Issue by Suraf** [StarCitizenWiki/mediawiki-extensions-EmbedVideo#73]
(First of all, thanks for reimplementing these back into the forked version of the extension! I'm sure communities beyond just Warcraft Wiki could really use them!)

**Describe the bug**
When those tags, vplayer or evlplayer is added like `<vplayer />` or `<evlplayer />`, they instead display this huge block that is otherwise empty.

The original experience, there was no empty block like this. Nothing. Whenever a video link is clicked (vlink or evl), this area would expand to that video.

**To Reproduce**
Just create an article and add `<vplayer />` or the other tag to the article.

Example:
https://warcraft.wiki.gg/wiki/Dragonflight_in-game_cinematics

![image](https://github.com/StarCitizenWiki/mediawiki-extensions-EmbedVideo/assets/19893933/3502d242-44be-4d34-9fca-9fc94eafddf5)

**Expected behavior**
There should be no big empty space where the video would appear if no default video id is provided.

So it should look like this:
![image](https://github.com/StarCitizenWiki/mediawiki-extensions-EmbedVideo/assets/19893933/086d6766-3870-48f2-b534-e32339806672)

When any of the video links is clicked, it expands and displays the video. It'll stay there forever, won't shrink back down or anything.
![image](https://github.com/StarCitizenWiki/mediawiki-extensions-EmbedVideo/assets/19893933/5e9567a2-13eb-4fda-a27e-ba7538d66af1)

**Technical information:**
 - OS: Windows 11
 - Browser: Firefox Developer Edition
 - Extension Version 3.4.0
 - MediaWiki Version 1.39.4
 - Host type: Wiki.gg

**Additional context**
Let me know if you'd like me to clarify anything.

**Comment by octfx** [comment]
That is currently expected behavior.  
You can hide the empty embed by adding the following css:
```css
.evlplayer[data-service="videolink"] {
  display: none;
}
```

I'll add this to the 3.4.1 release :)

**Comment by Suraf** [comment]
Sounds good, thanks!

**Comment by Suraf** [comment]
I can confirm that the `data-service` does not change at all from `videolink` after clicking a video link. I've tried it on this page: https://warcraft.wiki.gg/wiki/Shadowlands_in-game_cinematics
![data-service-videolink](https://github.com/StarCitizenWiki/mediawiki-extensions-EmbedVideo/assets/19893933/1b25634d-2a1b-4b1b-90d2-c0b8ed6fa492)

**Comment by octfx** [comment]
Was an oversight on my part! When explicit consent is not required, the service parameter was not updated.

Fixed in develop.
