### ISSUE TITLE
CSS class option not working?

### ISSUE THREAD

**Issue by SavageAlien** [StarCitizenWiki/mediawiki-extensions-EmbedVideo#74]
My wiki has local uploaded files we apply CSS classes to but have recently noticed that the classes are no longer being applied at all. 

Something like this: 
`[[File:SAMPLEVIDEO.mp4|class=CLASSNAME]]`

I'm wondering if the recent change to EmbedVideoUseEmbedStyleForLocalVideos is at all related? And is there a chance to have this class option return?

**Comment by octfx** [comment]
I don't know why the `class=` attribute wasn't passed to the output.

Added a fix in develop
