### ISSUE TITLE
vertical alignment property (vAlignment) not functioning

### ISSUE THREAD

**Issue by JoppyLoppy** [StarCitizenWiki/mediawiki-extensions-EmbedVideo#77]
**Describe the bug**
EmbedVideo elements will always stay aligned to the bottom of other EmbedVideo elements in the same line despite vAlignment property value, dimension property, or line breaks (if the video is small enough, and the description is long enough to line break).

The parameter vAlignment and its values (top, middle, bottom, baseline) don't effect the elements position at all. It appears that the property only adds the relevant class (e.g. class "mw-valign-baseline" for vAlignment=baseline), but the class doesn't have any styled properties.

**To Reproduce**
1. Go to [signalis.wiki.gg/wiki/Signalis](https://signalis.wiki.gg/wiki/Signalis)
2. In the top right of the page, click Edit to enter the source editor.
3. Scroll down to the relevant parser functions which are underneath the headers Media, Youtube, rose-engine. 
4. Adjust the dimensions of the embed videos to be smaller or larger than each other.
5. On the various #ev functions, change the vAlignment property to top, middle, bottom, or baseline.
6. Click "Show Preview" to preview the changes.
7. Unexpected behavior. EmbedVideo elements will always stay aligned to the bottom of other EmbedVideo elements in the same line despite vAlignment property value, dimensions, or line breaks (if the video is small enough, and the description is long enough to line break).

**Expected behavior**
- When adding vAlignment=top to an #ev function, I expect the embedded video to align its top to match the top of other embedded videos despite their lengths. However, even with vAlignment=middle, bottom, or baseline, the position of the elements don't change.

- When adding the vAlignment property with an argument, I expect some sort of property change when viewing the element in Developer Tools (Firefox), however, there doesn't seem to be anything linked to its class (e.g. "mw-valign-top").

**Screenshots**
![image](https://github.com/StarCitizenWiki/mediawiki-extensions-EmbedVideo/assets/59589451/79d46c9d-baca-4d70-aa33-caea5e65c992) caption: example of vAlignment=top when line-breaks are introduced and property dimensions are different from each other.
![image](https://github.com/StarCitizenWiki/mediawiki-extensions-EmbedVideo/assets/59589451/429f12a9-d895-41f8-ac1b-b39590a26ca2) caption: the behavior I expect when using vAlignment=top is for the tops of the elements (green lines) to be aligned with each other.
![image](https://github.com/StarCitizenWiki/mediawiki-extensions-EmbedVideo/assets/59589451/3d9fab30-da35-4732-b2c6-e2b06474ed78) caption: the class ("mw-valign-top") is there (and correctly changes based on the property value), but there doesn't seem to be any styling for it.

**Technical information:**
 - OS: [Windows 10
 - Browser: Firefox
 - Extension Version: 3.4.1
 - MediaWiki Version: 1.39.4
 - Host type: Wikifarm (Wiki.gg)

**Comment by octfx** [comment]
Sorry for the looong delay.

The underlying problem is that MW ships valign styles that do not match elements having `.mw-valign-*` classes.

I've now manually added these classes so the align does work now.

![image](https://github.com/StarCitizenWiki/mediawiki-extensions-EmbedVideo/assets/6594492/d774f064-747a-4038-ad65-0020660e3a5a)
