### ISSUE TITLE
Grey rectangle when embedding youtube video in version 3.4.1

### ISSUE THREAD

**Issue by pav00** [StarCitizenWiki/mediawiki-extensions-EmbedVideo#80]
Version 3.4.1 produces grey rectangle with the button Load video, no reaction from the button, no video available. Test used service youtube in the simplest settings, {{#ev:youtube|nQPrNVpSx3U}}, all parameters left to default. Downgrade to version 3.0.8 works.

**Screenshots**
![Embedvideo-ext-bug-3-4-1](https://github.com/StarCitizenWiki/mediawiki-extensions-EmbedVideo/assets/17032482/6afc5cdc-cace-4bed-8099-2d62736c7331)

**Technical information:**
[MediaWiki](https://www.mediawiki.org/) 	1.39.6
[PHP](https://php.net/) 	8.1.27 (fpm-fcgi)
[MariaDB](https://mariadb.org/) 	11.2.2-MariaDB
[ICU](https://icu.unicode.org/) 	74.2
[LilyPond](http://lilypond.org/) 	2.22.2
[Elasticsearch](https://www.elastic.co/elasticsearch) 	7.10.2

Tested browsers: Firefox, Chromium.

**Comment by octfx** [comment]
Do you have a live version to test?
This sounds like the resource loader providing out of date scripts.

Can you open the developer console (F12) and post possible errors from the console tab?

**Comment by pav00** [comment]
All caches were cleared for the test, which scripts from MW would you expect to be out of date? It is latest upgrade of MW.

**Comment by pav00** [comment]
No errors, only 21 warnings: 
Feature Policy: Skipping unsupported feature name “accelerometer”. Test
Feature Policy: Skipping unsupported feature name “clipboard-write”. Test
Feature Policy: Skipping unsupported feature name “encrypted-media”. Test
Feature Policy: Skipping unsupported feature name “gyroscope”. Test
Feature Policy: Skipping unsupported feature name “picture-in-picture”. Test
Feature Policy: Skipping unsupported feature name “autoplay”. Test
Feature Policy: Skipping unsupported feature name “accelerometer”. Test
Feature Policy: Skipping unsupported feature name “clipboard-write”. Test
Feature Policy: Skipping unsupported feature name “encrypted-media”. Test
Feature Policy: Skipping unsupported feature name “gyroscope”. Test
Feature Policy: Skipping unsupported feature name “picture-in-picture”. Test
Feature Policy: Skipping unsupported feature name “autoplay”. Test
Feature Policy: Skipping unsupported feature name “accelerometer”. Test
Feature Policy: Skipping unsupported feature name “clipboard-write”. Test
Feature Policy: Skipping unsupported feature name “encrypted-media”. Test
Feature Policy: Skipping unsupported feature name “gyroscope”. Test
Feature Policy: Skipping unsupported feature name “picture-in-picture”. Test
Feature Policy: Skipping unsupported feature name “autoplay”. Test
Partitioned cookie or storage access was provided to “https://www.youtube-nocookie.com/embed/nQPrNVpSx3U” because it is loaded in the third-party context and dynamic state partitioning is enabled.

Some cookies are misusing the recommended “SameSite“ attribute 2
Partitioned cookie or storage access was provided to “https://www.youtube.com/embed/Ips2KspFRzo?&iv_load_policy=3” because it is loaded in the third-party context and dynamic state partitioning is enabled.

Partitioned cookie or storage access was provided to “https://www.youtube.com/embed/Ips2KspFRzo?fs=0&modestbranding=1&playsinline=1&color=white&iv_load_policy=3” because it is loaded in the third-party context and dynamic state partitioning is enabled.

Some cookies are misusing the recommended “SameSite“ attribute 4
Some cookies are misusing the recommended “SameSite“ attribute 3
Some cookies are misusing the recommended “SameSite“ attribute 2

**Comment by octfx** [comment]
What are your EmbedVideo settings?

With no script errors showing this looks like the thumbnail failed to fetch.  
Either the request to YouTube was blocked or `$wgEmbedVideoFetchExternalThumbnails` is set to `false` (?)

The network tab for a successful thumbnail fetch should look something like this:
![image](https://github.com/StarCitizenWiki/mediawiki-extensions-EmbedVideo/assets/6594492/02c3c3f2-82a8-46ce-a71c-2fdc959f5c8e)

**Comment by pav00** [comment]
There are no blocks I would be also aware of, version 3.0.8 displays all videos normally, direct iframe in the page also works. Configuration settings have not been changed for ages, below:
#
wfLoadExtension( 'EmbedVideo' );
#
$wgEmbedVideoFetchExternalThumbnaiLs = 'true';
$wgEmbedVideoRequireConsent = 'false';
#

**Comment by octfx** [comment]
You need to set boolean values instead of strings like:
```php
$wgEmbedVideoFetchExternalThumbnaiLs = true;
$wgEmbedVideoRequireConsent = false;
```

**Comment by pav00** [comment]
Done. Thanks. The video loads now. Now the decision is whether to upgrade to 3.4.1 or stay with 3.0.8. There is additional wrapper in figure element in 3.4.1. In 3.0.8 it was possible to have a row of videos on the page with several lines of description that were aligned left under the video, will have to test whether it is possible to do the same arrangement with figure element in 3.4.1.
