### ISSUE TITLE
Embed Service Request: Spotify podcast episodes

### ISSUE THREAD

**Issue by Bongo50** [StarCitizenWiki/mediawiki-extensions-EmbedVideo#81]
**Service Name**
Spotify podcast episodes

**URL to an example embed**
https://open.spotify.com/episode/11mET6sr9ghOJ6mi4lmZmZ

**Additional notes**
Hopefully not too different to the other Spotify embeds.

**Comment by octfx** [comment]
Added in develop branch :)
