### ISSUE TITLE
Embed Service Request: Spotify podcast/shows

### ISSUE THREAD

**Issue by Bongo50** [StarCitizenWiki/mediawiki-extensions-EmbedVideo#82]
**Service Name**
Spotify podcasts/shows

**URL to an example embed**
https://open.spotify.com/show/7AWhoFQ3SIkEc6Yp1aOiIM

**Additional notes**
Hopefully not too different to the other Spotify embeds.

**Comment by octfx** [comment]
Added in develop branch :)
