### ISSUE TITLE
Make EmbedVideo compatible with PHP 7.4

### ISSUE THREAD

**Issue by bertrandgorge** [StarCitizenWiki/mediawiki-extensions-EmbedVideo#84]
The constraint to PHP 8 is not necessary and is blocking the extension from working properly with PHP 7.4 which is still required for some other extensions of MediaWiki 1.39 (such as Semantic Mediawiki)

**Comment by octfx** [comment]
The extension uses PHP 8 only functions in some places, just downgrading the version does not suffice. :/

While I know that MW is slow in picking up recent PHP versions, I don’t think it’s unreasonable requiring a version of PHP that was released over three years ago.
That being said, I’m running SMW on PHP 8 and 1.39 myself without any issues.

**Comment by alistair3149** [comment]
> ...While I know that MW is slow in picking up recent PHP versions, I don’t think it’s unreasonable requiring a version of PHP that was released over three years ago...

I agree, PHP 7.4 has been EOL for more than a year and it would be the best to avoid using it.
SMW does [support up to PHP 8.1.x officially](https://www.semantic-mediawiki.org/wiki/Help:Compatibility), and it would be best to file an issue in the relevant issue tracker if an extension does not support PHP 8.1. If the extension is on Gerrit, you can file a task through [Phabricator](https://phabricator.wikimedia.org/project/view/5132/) with the tag `PHP 8.1 support`.

**Comment by bertrandgorge** [comment]
Hello, I understand the rational although it makes things really complicated when you have a wiki with other extensions that are not yet compatible (including SMW when used with Elastic Search). For what it's worth I will keep my fork, as far as I could test it it works well with PHP 7.4 (unless there's a functionnality I haven't used).

**Comment by prodigion** [comment]
Ubuntu 20.04 is supported for another year and still runs on PHP 7.4.3 with backported security patches.
