### ISSUE TITLE
<lang>.json not loaded

### ISSUE THREAD

**Issue by MGVO-Hub** [StarCitizenWiki/mediawiki-extensions-EmbedVideo#86]
I installed EmbedVideo version 3.4.1 on Wikimedia 1.41.0 and recognized, that the 'lang'.json file (de.json in my case) is obviously not loaded. The placeholders "embedvideo-load", "embedvideo-service-vimeo" etc. appear on screen.
![Screenshot 2024-03-05 211541](https://github.com/StarCitizenWiki/mediawiki-extensions-EmbedVideo/assets/51966863/48b965d2-095c-4724-bad6-1996c5920351)

**Comment by octfx** [comment]
Weird, I'm using the exact configuration without having this error.

I've copied over the service names from `en` to `de` in [4d04ec1](https://github.com/StarCitizenWiki/mediawiki-extensions-EmbedVideo/commit/4d04ec182f6202161002b3f06a2afa66862b69d4).  
Could you see if this helps?

**Comment by MGVO-Hub** [comment]
Yes, this solved the issue.
Thanks a lot!
Dirk
