### ISSUE TITLE
Add curl extension to the requirements

### ISSUE THREAD

**Issue by Zankaria** [StarCitizenWiki/mediawiki-extensions-EmbedVideo#87]
Installing the extension I noticed it gave me a blank page on MediaWiki 1.39. Looking at the logs, it's due to `EmbedVideo` requiring the curl PHP extension to be installed.
Could you add it to the requirements?

**Comment by octfx** [comment]
EmbedVideo requires Guzzle, which should already be part of the main MW composer.

I've noticed though that ext-curl was erroneously still present in `extension.json`, which I've now removed.

**Comment by octfx** [comment]
Feel free to re-open when needed
