### ISSUE TITLE
Compatibility for autoresize=true to work with fixed height / width

### ISSUE THREAD

**Issue by D3nnis3n** [StarCitizenWiki/mediawiki-extensions-EmbedVideo#91]
Refering to my late answer here that likely won't ever get seen:
https://github.com/StarCitizenWiki/mediawiki-extensions-EmbedVideo/issues/26

## Detailed Description
It's super great that autoresize is now possible, so videos can adjust in size based on mobile / desktop or window ui size.
Unfortunately it always sizes it to the maximum size of the container it is in. The original plugin allowed using autoresize together with width / height, to limit the maximum size embed can have.

## Context
The goal in my case is to use the autoresize feature to ensure that when using smaller windows sizes or mobile  the user sees a resized video in smaller instead of cut off. At the same time it shouldn't be bigger than 640 in width, as otherwise preview images may not have high resolution:

![image](https://github.com/StarCitizenWiki/mediawiki-extensions-EmbedVideo/assets/25908592/b387f5c9-68e4-4a5f-a4e1-d307a7cf0580)
(Bad resolution, as sized bigger)

![image](https://github.com/StarCitizenWiki/mediawiki-extensions-EmbedVideo/assets/25908592/b56898f0-4aa8-42c7-9971-009f3da04c4c)
Good resolution as sized maximum 640px)

## Possible Implementation
The idea would either to add "maxwidth" and "maxheight" settings or just let autoresize respect given "width" and "height" directives as the maximum to resize to.

In the example above we use the following, having assumed it would do what we wanted like was possible with the original plugin.
`{{#ev:youtube|id=d6zvBdUDMPY|alignment=center|autoresize=true|width=640px}}`

Also please let me thank you once more for adding autoresize to begin with, I only saw it very late, but am very grateful for that!

**Comment by octfx** [comment]
This is now implemented in develop :)

![image](https://github.com/StarCitizenWiki/mediawiki-extensions-EmbedVideo/assets/6594492/8d37fb6d-8d53-4b7c-acee-0b9275e209cc)
Top is with `|width=640px` option, bottom is just with `|autoresize=true`

**Comment by D3nnis3n** [comment]
You're an absolute god. Thank you so much for investing your freetime, making others smile.
