### ISSUE TITLE
Remember if user already clicksed on "$service might collect personal data"

### ISSUE THREAD

**Issue by dolfinus** [StarCitizenWiki/mediawiki-extensions-EmbedVideo#92]
## Detailed Description

Currently every time an external video is played (such as YouTube), a pop-up window is shown:
"YouTube might collect personal data. _Link_"

It is ok if user just saw this message and clicked to proceed button. But this message is shown for every video, and user should approve this again and again.

Just remember the user choice and do not show this pop-up all the time.

**Comment by octfx** [comment]
EmbedVideo now remembers the given consent for the current session

**Comment by dolfinus** [comment]
Thanks!
