### ISSUE TITLE
Embedded Videos placed in galleries have too much height

### ISSUE THREAD

**Issue by betta7776** [StarCitizenWiki/mediawiki-extensions-EmbedVideo#94]
**Describe the bug**
When an embedded video is added to a gallery next to other images, the video cell of the gallery is slightly larger than the other cells. This happens regardless of if width and height are set or not. The example shown in this report is with height and width both set to 241px

**To Reproduce**
1. Go to https://helldivers.wiki.gg/index.php?title=Clapping&oldid=38064
2. view "Media" section
3. Compare first two images to the third video.

**Expected behavior**
All cells of the gallery should take up the same amount of vertical space in its default mode.

**Screenshots**
Current Behavior:
![image](https://github.com/StarCitizenWiki/mediawiki-extensions-EmbedVideo/assets/41590158/0185bb67-a8db-4ed0-b205-3e0e80aef307)

Desired Behavior:
![image](https://github.com/StarCitizenWiki/mediawiki-extensions-EmbedVideo/assets/41590158/fdfaf29c-bee1-49f1-a982-9350d44bcd3b)

**Technical information:**
 - OS: Windows 10
 - Browser: Chrome
 - Extension Version: 3.4.1
 - MediaWiki Version: 1.39
 - Host type: Wiki.gg

**Additional context**

**Comment by alistair3149** [comment]
Looks like it is the intended behavior from MediaWiki. 
The first image and the embed video have the exact same margin (`15px`) and height (`241px`), which is defined by the gallery syntax `heights="241px"`. The gallery is forcing all content to fit within both `241px` width and height. If you wish to force it to be the same height, unset the `widths` parameter in the `<gallery>` syntax, or use CSS to achieve it.

**Comment by betta7776** [comment]
Only width defined:
![image](https://github.com/StarCitizenWiki/mediawiki-extensions-EmbedVideo/assets/41590158/cddd40fd-853f-4cd3-be28-49b2fda9dba7)

Only height defined:
![image](https://github.com/StarCitizenWiki/mediawiki-extensions-EmbedVideo/assets/41590158/10621176-d131-477d-b403-6240497c9803)

Neither defined:
![image](https://github.com/StarCitizenWiki/mediawiki-extensions-EmbedVideo/assets/41590158/968f9509-687b-4811-9aa8-6f3abf7aa81e)


All three cases result in the embedded video slightly taller than the other cells. This is caused by a strange small extra gap under the video thumb element itself. We cannot figure out why that extra space is there by default. The space we are talking about is indicated by the red rectangle on the following screenshot:
![image](https://github.com/StarCitizenWiki/mediawiki-extensions-EmbedVideo/assets/41590158/146ec78f-d45f-4db4-8434-c21a05501dd3)

That weird gap shown in red can be removed by adding the following CSS to the embed, but I assume this functionality is indeed unintended and a bug.
```
.gallerybox figure.embedvideo {
    margin: auto; /* centers block */
    display: block; /* Eliminates weird gap at bottom */
}
```

**Comment by betta7776** [comment]
![image](https://github.com/StarCitizenWiki/mediawiki-extensions-EmbedVideo/assets/41590158/6928f34a-79f6-4219-836f-a1bb711b3a3c)
